version: "3.9"
services:
  db:
    image: postgres:16
    container_name: community-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: apppw
      POSTGRES_DB: appdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
      LANG: C.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data