version: "3.9"
services:
  db:
    image: postgres:16
    container_name: community-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: apppw
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data